# Site settings
title: "Foostats | Classements buteurs | Foot amateur Suisse"
title_de: "Torschützen-Ranglisten | Topscorers | Amateurfussball Schweiz"
description_de: "Torschützen- und Mannschafts-Rangliste für die Amateur-Meisterschaften der Kantone Waadt und Freiburg"
description: "Classements buteurs et équipes pour les championnats amateurs de football des cantons de Vaud et Fribourg"

baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://www.footstats.ch" # the base hostname & protocol for your site
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
name: "FOOTSTATS.CH"

# exclude: [dpackage.json,gulpfile.js,js/dev,node_modules,README.m]
languages: ["fr","de"]
exclude_from_localizations: ["palmares/2017","js", "images", "css", "rankings","_posts","aff","acvf","acgf","anf","avf","import","libs","stats","config_prod.yml","jobs.html","cgv.html","shop.html","conditions-concours.html","topbuts.html","service-worker.js"]
exclude: ["backup","oldapp","node_modules","swiss-team.html","Gemfile","Gemfile.lock","package.json","gulpfile.js","README.m","feed.xml","js/dev","app","*/global-stats.html","package-lock.json"]
gems: 
  - jekyll-multiple-languages-plugin
  - jekyll-sitemap
  - jekyll-paginate

future: true
paginate: 12
paginate_path: "/page:num/"

collections:
  archives:
    output: true